config/routes.rb
Project3::Application.routes.draw do
  resources :courses

  resources :categories

  devise_for :users

  resources :photos

  resources :bookmarks

  resources :ingredients

  resources :posts

  resources :comments

  root :to => 'static#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :ingredient, :post_id

  belongs_to :post
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.haml
= form_for @ingredient do |f|
  - if @ingredient.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ingredient.errors.count, "error")} prohibited this ingredient from being saved:"
      %ul
        - @ingredient.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :post_id
    = f.number_field :post_id
  .field
    = f.label :ingredient
    = f.text_field :ingredient
  .actions
    = f.submit 'Save'

app/views/ingredients/edit.html.haml
%h1 Editing ingredient

= render 'form'

= link_to 'Show', @ingredient
\|
= link_to 'Back', ingredients_path

app/views/ingredients/index.html.haml
%h1 Listing ingredients

%table
  %tr
    %th Post
    %th Ingredient
    %th
    %th
    %th

  - @ingredients.each do |ingredient|
    %tr
      %td= ingredient.post_id
      %td= ingredient.ingredient
      %td= link_to 'Show', ingredient
      %td= link_to 'Edit', edit_ingredient_path(ingredient)
      %td= link_to 'Destroy', ingredient, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Ingredient', new_ingredient_path

app/views/ingredients/new.html.haml
%h1 New ingredient

= render 'form'

= link_to 'Back', ingredients_path

app/views/ingredients/show.html.haml
%p#notice= notice

%p
  %b Post:
  = @ingredient.post_id
%p
  %b Ingredient:
  = @ingredient.ingredient

= link_to 'Edit', edit_ingredient_path(@ingredient)
\|
= link_to 'Back', ingredients_path